### ISSUE TITLE
是否考虑写一个跟immutable.js结合的版本？

### ISSUE THREAD

**Issue by zry656565** [yanhaijing/data.js#8]
在data.js中，存取数据都是需要经过深复制的，效率在某些情况下的确会存在一些问题。而结合immutable的概念，存取数据就不需要深复制，而是直接复制引用即可。

也许可以考虑以插件的形式，写一个跟[immutable.js](https://github.com/facebook/immutable-js)组合使用的版本？

**Comment by yanhaijing** [comment]
感谢反馈，我先看看这是啥东西

**Comment by yanhaijing** [comment]
@zry656565 大概了解，请问你是否愿意贡献一个？

**Comment by zry656565** [comment]
可以啊，有时间尝试做做看。

**Comment by yanhaijing** [comment]
@zry656565 感谢，可以提个pr，或者写个周边，感谢

**Comment by zry656565** [comment]
我思考了一下，觉得 data.js 如果要让用户用的时候感知不到 immutable.js 的存在，那两者结合的意义很小。只能是借助 `Immutable.fromJS()` 和 `Immutable.toJSON()` 来替代原本的深复制方法而已，为此引入一个 55k 的文件没有必要。

如果某个项目本身已经引入 Immutable.js，在 Data.get 时直接返回 Immutable.js 的对象，那样才比较有意义。不过我觉得那就应该另外开个项目了。。

**Comment by yanhaijing** [comment]
@zry656565 是否可以写个周边插件？需要我看个接口支持吗？

**Comment by zry656565** [comment]
写个 Immutable 的插件肯定没问题，而且实现起来的代码量应该也不大。你是说在初始化 Data 的时候传入一个参数来确定是否采用基于 Immutable.js 的方式？

**Comment by yanhaijing** [comment]
@zry656565 我是说为支持这个插件 我还需要改代码不

**Comment by zry656565** [comment]
应该会改一部分，我到时候给你发个 PR，你 review 一下吧。

**Comment by yanhaijing** [comment]
3q
